export enum EntityType {
    Unknown = 0,
    Dashboard = 1,
    Card = 2,
    Source = 3,
    Report = 4,
    Measure = 5,
    Account = 6,
    Text = 7,
    AnswerGroup = 8,
    DataConnector = 9,
    Score = 10,
    Group = 11,
    User = 12,
    Attribute = 13,
    AttributeScale = 14,
    CaseTypeMetadata = 15,
    ScriptedResponse = 16,
    AlertTypeMetadata = 17,
    GlobalMeasure = 18,
    Ontology = 19,
    StatisticalSignificance = 20,
    IgnoreMinimumResponse = 21,
    CaseRemoval = 22,
}
